title: Capboard API docs
description: API documentation for ESOP
theme: just-the-docs
color_scheme: blue


url: https://www.capboard.io/api/docs

aux_links:
  Endpoints List: https://www.capboard.io/api/docs/endpoints
